### ISSUE TITLE
Touchkit Error in Chrome browser version 85 issuue

### ISSUE THREAD

**Issue by mailtokarthik2003** [parttio/touchkit#21]
In our project we are using touchkit-5.0.0.beta1.jar   but it is working fine with chrome browser version 75 .Update chrome browser to version 85 .touchkit got some error 

Application Cache Error event: Invalid or missing manifest origin trial token: http://localhost:8081/web2schoolv8/VAADIN/widgetsets/AppWidgetset/safari.manifest
AppWidgetset-0.js:9413 Uncaught TypeError: Cannot read property 'addEventListener' of undefined
    at Oqg (AppWidgetset-0.js:9413)
    at Qqg (AppWidgetset-0.js:8582)
    at Array.bD (AppWidgetset-0.js:7956)
    at g (AppWidgetset-0.js:8224)
    at yi (AppWidgetset-0.js:3969)
    at Bi (AppWidgetset-0.js:8399)
    at eval (AppWidgetset-0.js:5827)
    at vMb (AppWidgetset-0.js:8225)
    at eval (AppWidgetset-0.js:9714)
    at <anonymous>:1:1
    at m (AppWidgetset.nocache.js:9)
    at AppWidgetset.nocache.js:10
    at HTMLDocument.d (AppWidgetset.nocache.js:6)
how to resolve this error but other browser it is running fine .

 So we change the version touchkit 5.0.1 it is also gave same error .

please give me some idea about this issue .

Very Urgent...

**Comment by TatuLund** [comment]
When you updated to Touchkit 5.0.1, did you re.compile the widgetset. I would also recommend to compile the widgetset in DETAILED mode, as the minified version of the stacktrace does not give much information.

**Comment by xylo** [comment]
There is a version 5.0.1?  Where did you find that one?
The latest version I can find in this repo is 5.0.0.beta2.  Even if I look into https://github.com/vaadin/touchkit I can only find a version 5.0-SNAPSHOT.

**Comment by xylo** [comment]
OK, I found it on https://vaadin.com/directory/component/touchkit, but isn't this addon open source? (Apache License 2)

**Comment by TatuLund** [comment]
> but isn't this addon open source? (Apache License 2)

Yes it is. Touchkit was commercial product up to version 4.0 with Vaadin 7. After that we decided to stop pro-active maintenance of it, and released 5.x with Apache License 2 for Vaadin 8 use.

**Comment by TatuLund** [comment]
Chrome 85 has removed support of AppCache. This may have caused issues. For sure Touchkit v4.x stopped working as it is using AppCache with all browsers.

However after this patch https://github.com/parttio/touchkit/commit/af55eb57d5c864263192eae0d1572b2ab882aa4d Touchkit 5 should use service worker with Chrome, and hence technically should be compatible with Chrome 85, unless there has been some minor thing accidentally left there. Note the change was made years ago during time there was no Chrome missing AppCache.

**Comment by xylo** [comment]
> > but isn't this addon open source? (Apache License 2)
> 
> Yes it is. Touchkit was commercial product up to version 4.0 with Vaadin 7. After that we decided to stop pro-active maintenance of it, and released 5.x with Apache License 2 for Vaadin 8 use.

OK.  I was just confused because https://vaadin.com/directory/component/touchkit/links links to this repo as the source of the code, but here I cannot find the source code of the current version (5.0.2).  Therefore 5.0.2 looked to me as not open source anymore.  Hope the source code is getting released as well at some point.

**Comment by mailtokarthik2003** [comment]
Chrome 85 has removed support of AppCache. This may have caused issues.Any New touchkit version available.otherwise how to solve the problem.Give me some solution.Very urgent....

**Comment by TatuLund** [comment]
I think this is fixed now by https://github.com/parttio/touchkit/commit/a52c1c128e6ea8b57cd9ed1bc47264ce33d416a6
