### ISSUE TITLE
touchkit problem updated chrome

### ISSUE THREAD

**Issue by Deepa266** [parttio/touchkit#22]
We Use Vaadin Version 8.2.0  group ID org.vaadin.touchkit Version touhkit5.0.0.beta1 the update chrome problem the screen refresh automatically after i change group ID org.vaadin.touchkit Version touhkit5.0.1  i have lot of error.

**Comment by TatuLund** [comment]
I think this is fixed by https://github.com/parttio/touchkit/commit/a52c1c128e6ea8b57cd9ed1bc47264ce33d416a6
